export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e7e2d9',
        primary: '#5a5653',
        outline: '#897267',
        'on-surface': '#1d1b16',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f6f0e7',
        'primary-container': '#736e6b',
        'secondary-container': '#fd8a42',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#76330d',
        'on-tertiary': '#ffffff',
        'on-background': '#1d1b16',
        'surface-container-low': '#f9f3ea',
        'on-secondary-fixed': '#331200',
        'on-secondary-fixed-variant': '#763300',
        'on-error-container': '#93000a',
        secondary: '#9b4500',
        'on-tertiary-fixed': '#351000',
        'tertiary-fixed-dim': '#ffb693',
        'surface-dim': '#dfd9d1',
        'surface-tint': '#625d5b',
        tertiary: '#8a421c',
        'on-error': '#ffffff',
        'surface-variant': '#e7e2d9',
        'tertiary-fixed': '#ffdbcc',
        'on-surface-variant': '#564338',
        'surface-container-high': '#ede7de',
        'surface-container': '#f3ede4',
        'tertiary-container': '#a85a32',
        'on-primary-fixed': '#1e1b19',
        'on-primary-fixed-variant': '#4a4643',
        background: '#fff9ef',
        surface: '#fff9ef',
        'primary-fixed': '#e9e1dd',
        'on-primary-container': '#faf2ee',
        'inverse-surface': '#32302a',
        'surface-bright': '#fff9ef',
        error: '#ba1a1a',
        'on-tertiary-container': '#fff0eb',
        'inverse-primary': '#ccc5c2',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'outline-variant': '#ddc1b3',
        'primary-fixed-dim': '#ccc5c2',
        'secondary-fixed': '#ffdbca',
        'secondary-fixed-dim': '#ffb68e',
        'on-secondary-container': '#682c00',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
